[global]
log_level = 'debug'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[[chains]]
id = '__FUND_CHAIN_ID__'
type = 'CosmosSdk'
rpc_addr = 'http://__FUND_RPC__'
grpc_addr = 'http://__FUND_GRPC__'
event_source = { mode = 'push', url = 'ws://__FUND_RPC__/websocket', batch_delay = '200ms' }
rpc_timeout = '15s'
trusted_node = true
account_prefix = 'und'
key_name = 'fund_relayer'
store_prefix = 'ibc'
gas_price = { price = 25.0, denom = 'nund' }
gas_multiplier = 1.2
default_gas = 1000000
max_gas = 10000000
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '2', denominator = '3' }

 [chains.packet_filter]
 policy = 'allow'
 list = [
#   ['ica*', '*'],
   ['transfer', 'channel-0'],
 ]

[[chains]]
id = '__IBC_CHAIN_ID__'
type = 'CosmosSdk'
rpc_addr = 'http://__IBC_GAIAD_RPC__'
grpc_addr = 'http://__IBC_GAIAD_GRPC__'
event_source = { mode = 'push', url = 'ws://__IBC_GAIAD_RPC__/websocket', batch_delay = '200ms' }
rpc_timeout = '15s'
trusted_node = true
account_prefix = 'cosmos'
key_name = 'simapp_relayer'
store_prefix = 'ibc'
gas_price = { price = 1, denom = 'stake' }
gas_multiplier = 1.2
default_gas = 1000000
max_gas = 10000000
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '2', denominator = '3' }

 [chains.packet_filter]
 policy = 'allow'
 list = [
#   ['ica*', '*'],
   ['transfer', 'channel-0'],
 ]
