[global]
log_level = 'info'
[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = true
[mode.connections]
enabled = false
[mode.channels]
enabled = false
[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true
[rest]
enabled = true
host = '0.0.0.0'
port = 3000
[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001
[[chains]]
id = '__FUND_CHAIN_ID__'
rpc_addr = 'http://__FUND_RPC__'
grpc_addr = 'http://__FUND_GRPC__'
websocket_addr = 'ws://__FUND_RPC__/websocket'
rpc_timeout = '10s'
account_prefix = 'und'
key_name = 'fund_relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 100000
max_gas = 700000
gas_price = { price = 25.0, denom = 'nund' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '600s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = ''
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-0'],
]

[[chains]]
id = '__IBC_CHAIN_ID__'
rpc_addr = 'http://__IBC_SIMD_RPC__'
grpc_addr = 'http://__IBC_SIMD_GRPC__'
websocket_addr = 'ws://__IBC_SIMD_RPC__/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'simapp_relayer'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 700000
gas_price = { price = 1, denom = 'stake' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 180000 # 90% of chain's consensus param max_size
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days' # < chain's unbonding period
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
[chains.packet_filter]
policy = 'allow'
list = [
    ['transfer', 'channel-0'],
]
